MODEL:
  META_ARCHITECTURE: "IDOL"
  WEIGHTS: "cocopretrain_R101.pth" #"./output/armbench_cp_semi_DPA_(0.99_0.5)/model_0013999.pth" # "cocopretrain_R101.pth" 
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  
  IDOL:
    NUM_CLASSES: 2
    MULTI_CLS_ON: True
DATASETS:
  TRAIN: ("armbench_train",)
  TEST: ("armbench_test",)
SOLVER:
  IMS_PER_BATCH: 1 #32
  BASE_LR: 0.0001
  STEPS: (10000,) #(8000,)
  MAX_ITER: 30000  #24000 
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 1000
INPUT:
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  RANDOM_FLIP: "flip_by_clip"
  # AUGMENTATIONS: []
  # MIN_SIZE_TRAIN: (360, 480)
  MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 600 #660 #768
  MIN_SIZE_TEST: 480
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: (0.9, 0.9)
  FORMAT: "RGB"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8
VERSION: 2
OUTPUT_DIR: output/armbench_1_100_semi_noDPA
SEMI: True
CLF_TH: .9
MASK_TH: 0.5
DPA: False

